using System;
using System.Collections.Generic;
using UnityEngine;

namespace AngryKoala.Data
{
    /// <summary>
    /// This class is generated by GameDataPropertyGenerator.
    /// Any changes may be overwritten.
    /// </summary>
    public partial class GameData : ScriptableObject
    {
        public int MaxLifeCount
        {
            get => _maxLifeCount;
            set => _maxLifeCount = value;
        }

        public int LifeReplenishDuration
        {
            get => _lifeReplenishDuration;
            set => _lifeReplenishDuration = value;
        }
    }
}