#if SRDEBUGGER

using System.ComponentModel;
using AngryKoala.Data;
using AngryKoala.Services;
using SRDebugger;

/// <summary>
/// This class is generated by DataPropertyGenerator - GameData.
/// Any changes may be overwritten.
/// </summary>
public partial class SROptions
{
    [Category("Game Data")]
    [DisplayName("Life Replenish Duration")]
    [Sort(1)]
    public int GameDataLifeReplenishDuration
    {
        get => DataService.GameData.LifeReplenishDuration;
        set => DataService.GameData.LifeReplenishDuration = value;
    }
}

#endif