using System;
using System.Collections.Generic;
using UnityEngine;

namespace AngryKoala.Data
{
    /// <summary>
    /// This class is generated by DataPropertyGenerator (SettingsData).
    /// Any changes may be overwritten.
    /// </summary>
    public partial class SettingsData : ScriptableObject
    {
        public bool MusicEnabled
        {
            get => _musicEnabled;
            set => _musicEnabled = value;
        }

        public bool SoundEnabled
        {
            get => _soundEnabled;
            set => _soundEnabled = value;
        }

        public bool VibrationEnabled
        {
            get => _vibrationEnabled;
            set => _vibrationEnabled = value;
        }
    }
}