#if SRDEBUGGER

using System.ComponentModel;
using AngryKoala.Data;
using AngryKoala.Services;
using SRDebugger;

/// <summary>
/// This class is generated by DataPropertyGenerator - SettingsData.
/// Any changes may be overwritten.
/// </summary>
public partial class SROptions
{

}

#endif