#if SRDEBUGGER

using System.ComponentModel;
using AngryKoala.Data;
using AngryKoala.Services;
using SRDebugger;

/// <summary>
/// This class is generated by DataPropertyGenerator - PlayerData.
/// Any changes may be overwritten.
/// </summary>
public partial class SROptions
{
    [Category("Player Data")]
    [DisplayName("Score")]
    [Sort(1)]
    public int PlayerDataScore
    {
        get => DataService.PlayerData.Score;
        set => DataService.PlayerData.Score = value;
    }
}

#endif