using System;
using System.Collections.Generic;
using UnityEngine;

namespace AngryKoala.Data
{
    /// <summary>
    /// This class is generated by PlayerDataPropertyGenerator.
    /// Any changes may be overwritten.
    /// </summary>
    public partial class PlayerData : ScriptableObject
    {
        public int Level
        {
            get => _level;
            set => _level = value;
        }

        public int Score
        {
            get => _score;
            set => _score = value;
        }
    }
}